project_id = "umjqoizuhfrxzjgrdvei"

[functions.smartcar-auth]
verify_jwt = false

[functions.smartcar-auth-callback]
verify_jwt = false

[functions.smartcar-webhook]
verify_jwt = false

[functions.smartcar-test-generator]
verify_jwt = false